#!/bin/bash

# Example dotenv file
export KIBANA_URL="http://localhost:5601"
export KIBANA_SPACE="default"

# Authentication API key
# export KIBANA_APIKEY=""

# Authentication Username and Password
# export KIBANA_USERNAME=""
# export KIBANA_PASSWORD=""
